<!------------------------------------------------------------------------------------------------->
# Research

<!------------------------------------------------------------------------------------------------->
## Articles

1. Study of Some Simple Approximations to the Non-Interacting Kinetic Energy Functional, 
2016-01-07, International	Journal of Quantum Chemistry, Edison Salazar, Pedro Guarderas,
Eduardo Ludeña, Mauricio Cornejo, Valentin Karasiev.


<!------------------------------------------------------------------------------------------------->
## Workshops and Seminars

1. Statistic and Finance for Actuarial Science, 2024-08-05 - 2024-09-21, Pontifical Catholic 
University of Ecuador, Quito, Ecuador, 80 hours.

2. Data analysis and actuarial modeling, 2022-02-23, Ecuadorian Actuarial Society, Quito, Ecuador, 
1 hour 45 minutes.

3. IFIP TC7 Conference of System Modeling and Optimization, 2021-08-30 - 2021-09-03, Quito, 
Ecuador 5 days.

4. Foundations and perspectives of the social security in Latin America, 2021-04-01
Julio Garavito Colombian School of EngineeringMaría Ivette Osorio Arévalo, 36 hours.

5. Pensions, Solvency and Actuary 4.0, 2019-11-05 - 2019-11-06, International Actuarial 
Association and Ecuadorian Actuarial Association, Quito, Ecuador 13 hours.

6. Workshop XIV Mathematics and its Applications, 2016-09-01 - 2016-09-05, Mathematics Department, 
National Polytechnic School, Quito, Ecuador2 days.

7. Item Analysis, 2016-03-30 - 2016-04-01, National Center of Evaluation of Higher Education 
(CENEVAL), Quito, Ecuador30 hours.

8. International Forum of Accreditation and Quality Assurance in Latin America, 2014-07-16 - 2014-07-17,
Mathematics Department, National Polytechnic School, Quito, Ecuador 4 days.

9, Accreditation based on the model ABET2014-02-06Litoral Polytechnic School, 
Guayaquil, Ecuador18 hours.